version: '3'

networks:
  dockernet1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.201.0/28

services:
  nginx:
    image: nginx:stable-alpine
    container_name: tracktik-challenge-nginx
    ports:
      - "8088:8080"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - dockernet1

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        user: www
        uid: 1000
        env: development
    container_name: tracktik-challenge-app
    environment:
      MEMORY_LIMIT: 128M
      POST_MAX_SIZE: 30M
      UPLOAD_MAX_FILESIZE: 30M
      XDEBUG_CONFIG: "remote_host=192.168.201.1 remote_enable=1 remote_port=9001"
      PHP_IDE_CONFIG: "serverName=xDebug"
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - dockernet1
